# Generated by Django 3.2.25 on 2024-10-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phno', models.IntegerField(default=1230)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('notspecified', 'Notspecified')], default='Notspecified', max_length=25)),
            ],
        ),
    ]
