# Generated by Django 3.2.25 on 2024-10-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=25)),
                ('admin_pass', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='appoinments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('dste', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], default='not specified', max_length=25)),
                ('phone_number', models.CharField(max_length=400)),
                ('payment', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
