# Generated by Django 3.2.25 on 2024-10-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0002_admin_log_appoinments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinments',
            old_name='dste',
            new_name='date',
        ),
    ]
