# Generated by Django 3.2.25 on 2024-10-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_rename_dste_appoinments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinments',
            name='status_choices',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not specified', 'not specified')], default='pending', max_length=100),
        ),
    ]
