# Generated by Django 3.2.25 on 2024-10-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0005_rename_status_choices_appoinments_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinments',
            name='booking_status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='signup_db',
            name='phno',
            field=models.CharField(max_length=200),
        ),
    ]
