# Generated by Django 3.2.25 on 2024-11-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0006_auto_20241028_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doctor_id', models.CharField(max_length=400)),
                ('uploadphoto', models.FileField(upload_to='')),
                ('department', models.CharField(max_length=200)),
            ],
        ),
    ]
